### PR TITLE
Experiment with a SVG/Canvas sort-of-agnostic backend

### PR DESCRIPTION
**Pull request by jacobp100**
Tests don't pass at all. Just wondering what you thought of the approach!

### CODE REVIEW

**Comment by jacobp100** [comment]
So there's a lot of added files. The main one is `backends.ts`, should give an idea of how the approach works

**Comment by jayrmotta** [comment]
I want to add a feature to an app I'm working on that renders a component as a png file in runtime and then I'd share it as a base64 image to apps like whatsapp and the like, but I wonder if the dependencies like canvas, cairo, pixman and pango wouldn't make my app just too heavy.

What do you guys think?

Thanks in advance

**Comment by jaredly** [comment]
ooh somehow I totally missed this PR. @jacobp100 I like the approach! Certainly makes things cleaner between the two.
@jayrmotta what would you use to render the png file? https://github.com/iddan/react-native-canvas is interesting, but it uses an embedded webview, which feels like it would be pretty slow.

**Comment by jacobp100** [comment]
@jaredly No worries! I've made something at https://github.com/jacobp100/react-image-export/ so I can iterate fast 😄. This project really helped though!

**Pull request closed without merging**
